version: '3.9'

services:
  app:
    container_name: softspace-app
    build:
      context: .
      dockerfile: Dockerfile.production
    command: >
      bash -c "poetry run alembic upgrade heads 
      && poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000"
    ports:
      - '8000:8000'
    env_file: .env
    depends_on:
      - db

  db:
    container_name: softspace-db
    image: postgres:15
    ports:
      - '5432:5432'
    env_file: .env
    restart: unless-stopped
    volumes:
      - .data/database:/var/lib/postgresql/data
