version: '3.9'

services:
  app:
    container_name: softspace-app
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - '8000:8000'
    env_file: .env
    volumes:
      - ./src:/app/src
    depends_on:
      - db

  db:
    container_name: softline-db
    image: postgres:15
    ports:
      - '5432:5432'
    env_file: .env
    restart: unless-stopped
    volumes:
      - .data/database:/var/lib/postgresql/data
